version: 0.2

phases:
  build:
    commands:
      - echo Getting the Vue App Index file...
      - aws s3 cp s3://$BUCKET/index.html tesselo/templates/app.html
      - echo Building the Zappa deploy image...
      - docker build -t tesselo_zappa -f DockerfileZappa .
      - echo Running management commands compress, collect, migrate...
      - chmod +x ./compress_collect_migrate.sh && ./compress_collect_migrate.sh
      - echo Deploying App to Lambda Stage $STAGE
      - docker run --rm --env AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY --env AWS_STORAGE_BUCKET_NAME_STATIC=$BUCKET tesselo_zappa zappa update $STAGE
      - echo Building the worker Docker image...
      - docker build -t tesselo -f DockerfileTesselo .
      - echo Logging in to Amazon ECR on us-east-1...
      - $(aws ecr get-login --region us-east-1)
      - echo Pushing the Docker image to us-east-1...
      - docker tag tesselo:latest 595064993071.dkr.ecr.us-east-1.amazonaws.com/tesselo:$STAGE
      - docker push 595064993071.dkr.ecr.us-east-1.amazonaws.com/tesselo:$STAGE
