version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region eu-central-1)
  build:
    commands:
      - echo "Started Docker Build ${CODEBUILD_BUILD_ID##*:}"
      - echo Building the Docker image...
      - docker build -t tesselo -f DockerfileTesselo .
      - echo Running tests on Docker image...
      - docker run --rm --env DEBUG=True tesselo /run.sh test
      - echo Pushing the Docker image...
      - docker tag tesselo:latest 595064993071.dkr.ecr.eu-central-1.amazonaws.com/tesselo:latest
      - docker push 595064993071.dkr.ecr.eu-central-1.amazonaws.com/tesselo:latest
      - "echo {\\\"image\\\":\\\"595064993071.dkr.ecr.eu-central-1.amazonaws.com/tesselo:latest}\\\"} > image.json"

artifacts:
  files:
    - 'image.json'
