# Generated by Django 2.1.7 on 2019-09-09 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classify', '0017_predictedlayer_legend'),
        ('sentinel', '0007_compositebuildschedule_continuous_scene_ingestion'),
        ('formulary', '0003_auto_20190830_1649'),
        ('raster_aggregation', '0021_auto_20190905_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAggregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregationarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raster_aggregation.AggregationArea')),
                ('aggregationlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raster_aggregation.AggregationLayer')),
                ('composite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sentinel.Composite')),
                ('formula', models.ForeignKey(blank=True, help_text='Leave empty for predicted layers.', null=True, on_delete=django.db.models.deletion.CASCADE, to='formulary.Formula')),
                ('predictedlayer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classify.PredictedLayer')),
                ('valuecountresult', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='raster_aggregation.ValueCountResult')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregationlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raster_aggregation.AggregationLayer')),
                ('composite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sentinel.Composite')),
                ('formula', models.ForeignKey(blank=True, help_text='Leave empty for predicted layers.', null=True, on_delete=django.db.models.deletion.CASCADE, to='formulary.Formula')),
                ('predictedlayer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classify.PredictedLayer')),
            ],
        ),
    ]
