# Generated by Django 2.1.7 on 2019-12-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20191209_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportschedule',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
