# Generated by Django 2.1.7 on 2020-02-29 08:22

from django.db import migrations


def forward(apps, schema_editor):
    ReportAggregation = apps.get_model("report", "ReportAggregation")
    for agg in ReportAggregation.objects.all():
        if agg.composite:
            src_object = agg.composite
        elif agg.predictedlayer:
            src_object = agg.predictedlayer
        else:
            continue

        agg.min_date = src_object.min_date
        agg.max_date = src_object.max_date

        agg.save()


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20200229_0822'),
        ('classify', '0030_auto_20200228_1417'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
