# Generated by Django 2.1.7 on 2020-03-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20200229_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportaggregation',
            name='max_date',
            field=models.DateField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='reportaggregation',
            name='min_date',
            field=models.DateField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
