# Generated by Django 2.1.7 on 2020-03-06 14:57

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_auto_20200303_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportaggregation',
            name='stats_avg',
            field=models.FloatField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='reportaggregation',
            name='stats_cumsum_t0',
            field=models.FloatField(blank=True, editable=False, help_text='Nr of pixels counted.', null=True),
        ),
        migrations.AddField(
            model_name='reportaggregation',
            name='stats_cumsum_t1',
            field=models.FloatField(blank=True, editable=False, help_text='Sum of pixel values.', null=True),
        ),
        migrations.AddField(
            model_name='reportaggregation',
            name='stats_cumsum_t2',
            field=models.FloatField(blank=True, editable=False, help_text='Sum of squares of pixel values.', null=True),
        ),
        migrations.AddField(
            model_name='reportaggregation',
            name='stats_max',
            field=models.FloatField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='reportaggregation',
            name='stats_min',
            field=models.FloatField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='reportaggregation',
            name='stats_std',
            field=models.FloatField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='reportaggregation',
            name='value',
            field=django.contrib.postgres.fields.hstore.HStoreField(db_index=True, default=dict),
        ),
        migrations.AddField(
            model_name='reportaggregation',
            name='value_percentage',
            field=django.contrib.postgres.fields.hstore.HStoreField(db_index=True, default=dict),
        ),
    ]
