# Generated by Django 3.0.5 on 2020-04-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_auto_20200309_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportaggregation',
            name='stats_percentage_covered',
            field=models.FloatField(blank=True, editable=False, help_text='Percentage of area covered by valid pixels.', null=True),
        ),
    ]
