# Generated by Django 3.0.7 on 2020-07-01 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster_aggregation', '0025_auto_20200417_0337'),
        ('report', '0011_reportaggregation_stats_percentage_covered'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportaggregation',
            name='srid',
            field=models.IntegerField(default=3857, editable=False, help_text='SRID used for this aggregation.'),
        ),
        migrations.CreateModel(
            name='ReportAggregationLayerSrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srid', models.IntegerField(help_text='Specify an SRID for computing all aggregations on this layer.')),
                ('aggregationlayer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='raster_aggregation.AggregationLayer')),
            ],
        ),
    ]
