# Generated by Django 3.0.7 on 2020-07-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_auto_20200701_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportaggregationlayersrid',
            name='srid',
            field=models.IntegerField(help_text='Specify an SRID for computing all aggregations on this layer. The unit of the srid is required to be in meters.'),
        ),
    ]
