# Generated by Django 3.0.8 on 2021-03-08 10:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_auto_20200709_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportaggregation',
            name='value',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_index=True, default=dict),
        ),
        migrations.AlterField(
            model_name='reportaggregation',
            name='value_percentage',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_index=True, default=dict),
        ),
    ]
