# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 10:50
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('formula', models.TextField()),
                ('min_val', models.FloatField()),
                ('max_val', models.FloatField()),
                ('breaks', models.IntegerField(default=5)),
                ('color_palette', models.CharField(choices=[('BrBG', 'BrBG'), ('PRGn', 'PRGn'), ('PiYG', 'PiYG'), ('PuOr', 'PuOr'), ('RdBu', 'RdBu'), ('RdGy', 'RdGy'), ('RdYlBu', 'RdYlBu'), ('RdYlGn', 'RdYlGn'), ('Spectral', 'Spectral'), ('Blues', 'Blues'), ('Greens', 'Greens'), ('Greys', 'Greys'), ('Oranges', 'Oranges'), ('Purples', 'Purples'), ('Reds', 'Reds'), ('BuGn', 'BuGn'), ('BuPu', 'BuPu'), ('GnBu', 'GnBu'), ('OrRd', 'OrRd'), ('PuBuGn', 'PuBuGn'), ('PuBu', 'PuBu'), ('PuRd', 'PuRd'), ('RdPu', 'RdPu'), ('YlGnBu', 'YlGnBu'), ('YlGn', 'YlGn'), ('YlOrBr', 'YlOrBr'), ('YlOrRd', 'YlOrRd')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FormulaGroupObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.Formula')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormulaUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.Formula')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicFormula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
                ('formula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='formulary.Formula')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='formulauserobjectpermission',
            unique_together=set([('user', 'permission', 'content_object')]),
        ),
        migrations.AlterUniqueTogether(
            name='formulagroupobjectpermission',
            unique_together=set([('group', 'permission', 'content_object')]),
        ),
    ]
