# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0002_create_perms_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='acronym',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='formula',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
