# Generated by Django 2.1.7 on 2019-08-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0002_auto_20180925_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='rgb',
            field=models.BooleanField(default=False, help_text='Choose RGB vs Formula mode. If true the layer is rendered as RGB, otherwise as raster algebra.'),
        ),
        migrations.AddField(
            model_name='formula',
            name='rgb_alpha',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='formula',
            name='rgb_enhance_brightness',
            field=models.FloatField(blank=True, default=3.0, null=True),
        ),
        migrations.AddField(
            model_name='formula',
            name='rgb_enhance_color',
            field=models.FloatField(blank=True, default=1.9, null=True),
        ),
        migrations.AddField(
            model_name='formula',
            name='rgb_enhance_contrast',
            field=models.FloatField(blank=True, default=1.5, null=True),
        ),
        migrations.AddField(
            model_name='formula',
            name='rgb_enhance_sharpness',
            field=models.FloatField(blank=True, default=1.2, null=True),
        ),
        migrations.AddField(
            model_name='formula',
            name='rgb_scale_max',
            field=models.FloatField(blank=True, default=10000.0, null=True),
        ),
        migrations.AddField(
            model_name='formula',
            name='rgb_scale_min',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='formula',
            name='breaks',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='formula',
            name='color_palette',
            field=models.CharField(blank=True, choices=[('BrBG', 'BrBG'), ('PRGn', 'PRGn'), ('PiYG', 'PiYG'), ('PuOr', 'PuOr'), ('RdBu', 'RdBu'), ('RdGy', 'RdGy'), ('RdYlBu', 'RdYlBu'), ('RdYlGn', 'RdYlGn'), ('Spectral', 'Spectral'), ('Blues', 'Blues'), ('Greens', 'Greens'), ('Greys', 'Greys'), ('Oranges', 'Oranges'), ('Purples', 'Purples'), ('Reds', 'Reds'), ('BuGn', 'BuGn'), ('BuPu', 'BuPu'), ('GnBu', 'GnBu'), ('OrRd', 'OrRd'), ('PuBuGn', 'PuBuGn'), ('PuBu', 'PuBu'), ('PuRd', 'PuRd'), ('RdPu', 'RdPu'), ('YlGnBu', 'YlGnBu'), ('YlGn', 'YlGn'), ('YlOrBr', 'YlOrBr'), ('YlOrRd', 'YlOrRd')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formula',
            name='formula',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formula',
            name='max_val',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formula',
            name='min_val',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
