# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 16:32
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('sentinel', '0026_auto_20170925_1653'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formulary', '0003_auto_20170911_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicWMTSLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WMTSLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('formula', models.ForeignKey(help_text='Assumes RGB mode if left blank.', null=True, on_delete=django.db.models.deletion.CASCADE, to='formulary.Formula')),
                ('sentineltile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentinel.SentinelTile')),
            ],
        ),
        migrations.CreateModel(
            name='WMTSLayerGroupObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.WMTSLayer')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WMTSLayerUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.WMTSLayer')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='publicwmtslayer',
            name='wmtslayer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='formulary.WMTSLayer'),
        ),
        migrations.AlterUniqueTogether(
            name='wmtslayeruserobjectpermission',
            unique_together=set([('user', 'permission', 'content_object')]),
        ),
        migrations.AlterUniqueTogether(
            name='wmtslayergroupobjectpermission',
            unique_together=set([('group', 'permission', 'content_object')]),
        ),
    ]
