# Generated by Django 2.1.7 on 2019-12-12 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0018_auto_20190910_1121'),
        ('formulary', '0003_auto_20190830_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedLayerFormula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Key used for this layer in formula expression. Should only contain alphanumeric characters and no whitespace.', max_length=20)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.Formula')),
                ('predictedlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classify.PredictedLayer')),
            ],
        ),
    ]
