# Generated by Django 2.1.7 on 2020-02-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0004_predictedlayerformula'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='rgb_platform',
            field=models.CharField(choices=[('S1', 'Sentinel-1'), ('S2', 'Sentinel-2')], default='S2', help_text='Choose Platform for RGB interpretation.', max_length=20),
        ),
    ]
