# Generated by Django 2.0.2 on 2018-06-15 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0005_create_perms_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wmtslayer',
            name='formula',
            field=models.ForeignKey(blank=True, help_text='Assumes RGB mode if left blank.', null=True, on_delete=django.db.models.deletion.CASCADE, to='formulary.Formula'),
        ),
    ]
