# Generated by Django 3.0.8 on 2020-09-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0005_formula_rgb_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='discrete',
            field=models.BooleanField(default=False),
        ),
    ]
