# Generated by Django 3.0.8 on 2020-09-16 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0040_merge_20190313_1143'),
        ('formulary', '0006_formula_discrete'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='legend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='raster.Legend'),
        ),
    ]
