# Generated by Django 2.0.2 on 2018-07-12 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0006_auto_20180615_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicwmtslayer',
            name='wmtslayer',
        ),
        migrations.RemoveField(
            model_name='wmtslayer',
            name='formula',
        ),
        migrations.RemoveField(
            model_name='wmtslayer',
            name='sentineltile',
        ),
        migrations.AlterUniqueTogether(
            name='wmtslayergroupobjectpermission',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='wmtslayergroupobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='wmtslayergroupobjectpermission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='wmtslayergroupobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='wmtslayeruserobjectpermission',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='wmtslayeruserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='wmtslayeruserobjectpermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='wmtslayeruserobjectpermission',
            name='user',
        ),
        migrations.DeleteModel(
            name='PublicWMTSLayer',
        ),
        migrations.DeleteModel(
            name='WMTSLayer',
        ),
        migrations.DeleteModel(
            name='WMTSLayerGroupObjectPermission',
        ),
        migrations.DeleteModel(
            name='WMTSLayerUserObjectPermission',
        ),
    ]
