# Generated by Django 3.0.8 on 2020-09-28 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0015_auto_20200525_0822'),
        ('formulary', '0007_formula_legend'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='composite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sentinel.Composite'),
        ),
    ]
