# Generated by Django 3.0.5 on 2020-05-08 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wmts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wmtslayer',
            name='composite',
        ),
        migrations.RemoveField(
            model_name='wmtslayer',
            name='formula',
        ),
        migrations.RemoveField(
            model_name='wmtslayer',
            name='predictedlayer',
        ),
        migrations.RemoveField(
            model_name='wmtslayer',
            name='sentineltile',
        ),
        migrations.AlterUniqueTogether(
            name='wmtslayergroupobjectpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wmtslayergroupobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='wmtslayergroupobjectpermission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='wmtslayergroupobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='wmtslayeruserobjectpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wmtslayeruserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='wmtslayeruserobjectpermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='wmtslayeruserobjectpermission',
            name='user',
        ),
        migrations.DeleteModel(
            name='PublicWMTSLayer',
        ),
        migrations.DeleteModel(
            name='WMTSLayer',
        ),
        migrations.DeleteModel(
            name='WMTSLayerGroupObjectPermission',
        ),
        migrations.DeleteModel(
            name='WMTSLayerUserObjectPermission',
        ),
    ]
