# Generated by Django 2.0.2 on 2018-07-13 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0016_auto_20180625_1426'),
        ('wmts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmtslayer',
            name='predictedlayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classify.PredictedLayer'),
        ),
    ]
