# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0037_auto_20161128_1040'),
        ('raster_api', '0002_auto_20170508_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicRasterLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
                ('rasterlayer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='raster.RasterLayer')),
            ],
        ),
    ]
