# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-05-11 13:40
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0038_merge_20170509_1003'),
        ('raster_api', '0003_publicrasterlayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicLegend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
                ('legend', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='raster.Legend')),
            ],
        ),
    ]
