# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-05-22 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raster_api', '0006_auto_20170512_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legendsemanticsgroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raster.LegendSemantics'),
        ),
        migrations.AlterField(
            model_name='legendsemanticsuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raster.LegendSemantics'),
        ),
    ]
