# Generated by Django 3.0.8 on 2021-06-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster_api', '0006_auto_20200407_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readonlytoken',
            name='created',
            field=models.DateTimeField(help_text='This date serves as expiry date. The token is valid up to that date plus two weeks.'),
        ),
    ]
