# Generated by Django 3.0.8 on 2021-06-09 17:34

from django.db import migrations, models

import raster_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('raster_api', '0007_auto_20210609_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='readonlytoken',
            name='expiration_date',
            field=models.DateTimeField(default=raster_api.models.get_expiration_date),
        ),
        migrations.AlterField(
            model_name='readonlytoken',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
