# Generated by Django 3.0.8 on 2021-06-11 13:03
from datetime import timedelta

from django.db import migrations


def copy_created_date_to_expiration_date(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    ReadOnlyToken = apps.get_model('raster_api', 'ReadOnlyToken')
    for tok in ReadOnlyToken.objects.all():
        # Before adding the expiration date, the creation date was used as the
        # base for the expiration. So we set the default expiration date to the
        # creation date.
        tok.expiration_date = tok.created + timedelta(days=14)
        tok.save()


class Migration(migrations.Migration):

    dependencies = [
        ('raster_api', '0008_auto_20210609_1734'),
    ]

    operations = [
        migrations.RunPython(copy_created_date_to_expiration_date),
    ]
