# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-01 14:05
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raster_aggregation', '0014_auto_20170601_0550'),
        ('auth', '0008_alter_user_username_max_length'),
        ('raster_api', '0009_auto_20170522_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicValueCountResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
                ('valuecountresult', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='raster_aggregation.ValueCountResult')),
            ],
        ),
        migrations.CreateModel(
            name='ValueCountResultGroupObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raster_aggregation.ValueCountResult')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValueCountResultUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raster_aggregation.ValueCountResult')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='valuecountresultuserobjectpermission',
            unique_together=set([('user', 'permission', 'content_object')]),
        ),
        migrations.AlterUniqueTogether(
            name='valuecountresultgroupobjectpermission',
            unique_together=set([('group', 'permission', 'content_object')]),
        ),
    ]
