# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 16:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('sentinel', '0024_sentineltileaggregationarea'),
        ('raster_api', '0014_create_perms_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicSentinelTileAggregationArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
                ('sentineltileaggregationarea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sentinel.SentinelTileAggregationArea')),
            ],
        ),
        migrations.CreateModel(
            name='SentinelTileAggregationAreaGroupObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentinel.SentinelTileAggregationArea')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SentinelTileAggregationAreaUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentinel.SentinelTileAggregationArea')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='sentineltileaggregationareauserobjectpermission',
            unique_together=set([('user', 'permission', 'content_object')]),
        ),
        migrations.AlterUniqueTogether(
            name='sentineltileaggregationareagroupobjectpermission',
            unique_together=set([('group', 'permission', 'content_object')]),
        ),
    ]
