# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster_api', '0015_auto_20170905_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicSentinelTileAggregationLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SentinelTileAggregationLayerGroupObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SentinelTileAggregationLayerUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='publicsentineltileaggregationarea',
            name='sentineltileaggregationarea',
        ),
        migrations.AlterUniqueTogether(
            name='sentineltileaggregationareagroupobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='sentineltileaggregationareagroupobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='sentineltileaggregationareagroupobjectpermission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='sentineltileaggregationareagroupobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='sentineltileaggregationareauserobjectpermission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='sentineltileaggregationareauserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='sentineltileaggregationareauserobjectpermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='sentineltileaggregationareauserobjectpermission',
            name='user',
        ),
        migrations.DeleteModel(
            name='PublicSentinelTileAggregationArea',
        ),
        migrations.DeleteModel(
            name='SentinelTileAggregationAreaGroupObjectPermission',
        ),
        migrations.DeleteModel(
            name='SentinelTileAggregationAreaUserObjectPermission',
        ),
    ]
