# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raster_api', '0017_auto_20170925_1653'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorldLayerGroupGroupObjectPermission',
            new_name='CompositeGroupObjectPermission',
        ),
        migrations.RenameModel(
            old_name='WorldLayerGroupUserObjectPermission',
            new_name='CompositeUserObjectPermission',
        ),
        migrations.RenameModel(
            old_name='PublicWorldLayerGroup',
            new_name='PublicComposite',
        ),
    ]
