# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raster_api', '0018_auto_20180110_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publiccomposite',
            old_name='worldlayergroup',
            new_name='composite',
        ),
    ]
