# Generated by Django 2.0.2 on 2018-05-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raster_api', '0021_auto_20180220_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicvaluecountresult',
            name='valuecountresult',
        ),
        migrations.AlterUniqueTogether(
            name='valuecountresultgroupobjectpermission',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='valuecountresultgroupobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='valuecountresultgroupobjectpermission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='valuecountresultgroupobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='valuecountresultuserobjectpermission',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='valuecountresultuserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='valuecountresultuserobjectpermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='valuecountresultuserobjectpermission',
            name='user',
        ),
        migrations.DeleteModel(
            name='PublicValueCountResult',
        ),
        migrations.DeleteModel(
            name='ValueCountResultGroupObjectPermission',
        ),
        migrations.DeleteModel(
            name='ValueCountResultUserObjectPermission',
        ),
    ]
