# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 12:00
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BucketParseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude_band', models.CharField(max_length=3)),
                ('start', models.DateTimeField(auto_now=True)),
                ('end', models.DateTimeField(null=True)),
                ('log', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='MGRSTile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utmzone', models.CharField(max_length=2)),
                ('latitude_band', models.CharField(max_length=1)),
                ('grid_square', models.CharField(max_length=2)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='SentinelTile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.TextField(unique=True)),
                ('datastrip', models.TextField()),
                ('product_name', models.TextField()),
                ('tile_data_geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('collected', models.DateTimeField()),
                ('cloudy_pixel_percentage', models.FloatField()),
                ('data_coverage_percentage', models.FloatField()),
                ('mgrstile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentinel.MGRSTile')),
            ],
        ),
    ]
