# Generated by Django 2.0.2 on 2018-09-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composite',
            options={'permissions': (('view_composite', 'View composite'),)},
        ),
        migrations.AlterModelOptions(
            name='compositebuild',
            options={'permissions': (('view_compositebuild', 'View composite build'),)},
        ),
        migrations.AlterModelOptions(
            name='sentineltile',
            options={'permissions': (('view_sentineltile', 'View sentinel tile'),)},
        ),
    ]
