# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 09:36
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0032_auto_20160426_0152'),
        ('sentinel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestedSentinelTile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='raster.RasterLayer')),
                ('tile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sentinel.SentinelTile')),
            ],
        ),
        migrations.AlterField(
            model_name='bucketparselog',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
