# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 05:41
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0032_auto_20160426_0152'),
        ('sentinel', '0002_auto_20160509_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentinelTileBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(choices=[('B01.jp2', 'Band 1 - Coastal aerosol, WL 0.443 mu, RES 60 m'), ('B02.jp2', 'Band 2 - Blue, WL 0.490 mu, RES 10 m'), ('B03.jp2', 'Band 3 - Green, WL 0.560 mu, RES 10 m'), ('B03.jp2', 'Band 4 - Red WL 0.665 mu, RES 10m'), ('B04.jp2', 'Band 5 - Vegetation Red Edge, WL 0.705, RES 20 m'), ('B05.jp2', 'Band 6 - Vegetation Red Edge, WL 0.740, RES 20 m'), ('B06.jp2', 'Band 7 - Vegetation Red Edge, WL 0.783, RES 20 m'), ('B07.jp2', 'Band 8 - NIR, WL 0.842, RES 10 m'), ('B8A.jp2', 'Band 8A - Vegetation Red Edge, WL 0.865, RES 20 m'), ('B09.jp2', 'Band 9 - Water vapour, WL 0.945, RES 60 m'), ('B10.jp2', 'Band 10 - SWIR - Cirrus, WL 1.375, RES 60 m'), ('B11.jp2', 'Band 11 - SWIR, WL 1.610, RES 20 m'), ('B12.jp2', 'Band 12 - SWIR, WL 2.190, RES 20 m')], max_length=7)),
                ('layer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='raster.RasterLayer')),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentinel.SentinelTile')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingestedsentineltile',
            name='layer',
        ),
        migrations.RemoveField(
            model_name='ingestedsentineltile',
            name='tile',
        ),
        migrations.DeleteModel(
            name='IngestedSentinelTile',
        ),
    ]
