# Generated by Django 2.0.5 on 2018-10-23 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0003_auto_20181012_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositebuild',
            name='cloud_classifier',
            field=models.ForeignKey(blank=True, help_text='Use a classifier based cloud removal. The classifier is assumed to return a cloud probability or rank (the higher the output the more likely its a cloud). If specified, the cloud_version flag is ignored.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='classify.Classifier'),
        ),
        migrations.AlterField(
            model_name='sentineltile',
            name='status',
            field=models.CharField(choices=[('Unprocessed', 'Unprocessed'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Finished', 'Finished'), ('Failed', 'Failed'), ('Broken', 'Broken')], default='Unprocessed', max_length=20),
        ),
    ]
