# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-05-19 04:48
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0004_auto_20160518_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentineltile',
            name='tile_data_geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
