# -*- coding: utf-8 -*-
# Generated by Django 1.9.8.dev20160616122412 on 2016-06-30 03:41
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0005_auto_20160519_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
