# -*- coding: utf-8 -*-
# Generated by Django 1.9.8.dev20160616122412 on 2016-06-30 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0006_zoneofinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoneofinterest',
            name='currently_building',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zoneofinterest',
            name='last_built',
            field=models.DateTimeField(null=True),
        ),
    ]
