# Generated by Django 2.1.7 on 2019-07-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0006_auto_20190711_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositebuildschedule',
            name='continuous_scene_ingestion',
            field=models.BooleanField(default=False),
        ),
    ]
