# -*- coding: utf-8 -*-
# Generated by Django 1.9.8.dev20160616122412 on 2016-07-08 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0007_auto_20160630_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoneofinterest',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
