# -*- coding: utf-8 -*-
# Generated by Django 1.9.8.dev20160616122412 on 2016-09-12 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0009_auto_20160712_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucketparselog',
            old_name='latitude_band',
            new_name='utm_zone',
        ),
    ]
