# Generated by Django 2.2.9 on 2020-04-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0009_auto_20200207_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositeband',
            name='band',
            field=models.CharField(choices=[('B01.jp2', 'Band 1 - Coastal aerosol, WL 0.443 mu, RES 60 m'), ('B02.jp2', 'Band 2 - Blue, WL 0.490 mu, RES 10 m'), ('B03.jp2', 'Band 3 - Green, WL 0.560 mu, RES 10 m'), ('B04.jp2', 'Band 4 - Red WL 0.665 mu, RES 10m'), ('B05.jp2', 'Band 5 - Vegetation Red Edge, WL 0.705, RES 20 m'), ('B06.jp2', 'Band 6 - Vegetation Red Edge, WL 0.740, RES 20 m'), ('B07.jp2', 'Band 7 - Vegetation Red Edge, WL 0.783, RES 20 m'), ('B08.jp2', 'Band 8 - NIR, WL 0.842, RES 10 m'), ('B8A.jp2', 'Band 8A - Vegetation Red Edge, WL 0.865, RES 20 m'), ('B09.jp2', 'Band 9 - Water vapour, WL 0.945, RES 60 m'), ('B10.jp2', 'Band 10 - SWIR - Cirrus, WL 1.375, RES 60 m'), ('B11.jp2', 'Band 11 - SWIR, WL 1.610, RES 20 m'), ('B12.jp2', 'Band 12 - SWIR, WL 2.190, RES 20 m'), ('SCL.jp2', 'SCL - Scene Class, RES 20 m'), ('VV', 'VV Polarization'), ('VH', 'VH Polarization'), ('HH', 'HH Polarization'), ('HV', 'HV Polarization')], max_length=7),
        ),
    ]
