# Generated by Django 2.2.9 on 2020-04-09 19:19

from django.db import migrations
from sentinel.utils import populate_raster_metadata

SCL = 'SCL.jp2'


def forward(apps, schema_editor):
    """
    Create SCL composite bands for existing composites.
    """
    RasterLayer = apps.get_model("raster", "RasterLayer")
    RasterLayerMetadata = apps.get_model("raster", "RasterLayerMetadata")
    RasterLayerParseStatus = apps.get_model("raster", "RasterLayerParseStatus")
    Composite = apps.get_model("sentinel", "Composite")
    CompositeBand = apps.get_model("sentinel", "CompositeBand")
    for comp in Composite.objects.all():
        # Skip if band already exists.
        if comp.compositeband_set.filter(band=SCL).exists():
            continue
        # Create new raster.
        raster = RasterLayer.objects.create(name='{0} - {1}'.format(comp.name, SCL))
        RasterLayerMetadata.objects.create(rasterlayer=raster)
        RasterLayerParseStatus.objects.create(rasterlayer=raster)
        # Populate metadata.
        populate_raster_metadata(raster)
        # Set raster to compositeband.
        CompositeBand.objects.create(band=SCL, composite=comp, rasterlayer=raster)


def backward(apps, schema_editor):
    CompositeBand = apps.get_model("sentinel", "CompositeBand")
    for bnd in CompositeBand.objects.filter(band=SCL):
        bnd.rasterlayer.delete()
        bnd.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0010_auto_20200409_1934'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
