# -*- coding: utf-8 -*-
# Generated by Django 1.9.8.dev20160919103735 on 2016-10-12 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0012_auto_20160915_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentineltile',
            name='angle_altitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sentineltile',
            name='angle_azimuth',
            field=models.FloatField(default=0),
        ),
    ]
