# Generated by Django 3.0.5 on 2020-05-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0012_auto_20200507_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composite',
            name='official',
        ),
    ]
