# -*- coding: utf-8 -*-
# Generated by Django 1.10.4.dev20161124100321 on 2016-11-28 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0014_worldlayergroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoneofinterest',
            name='currently_building',
        ),
        migrations.RemoveField(
            model_name='zoneofinterest',
            name='last_built',
        ),
    ]
