# -*- coding: utf-8 -*-
# Generated by Django 1.10.4.dev20161207182842 on 2016-12-16 08:52
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0015_auto_20161128_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldParseProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('worldlayergroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentinel.WorldLayerGroup')),
                ('zoneofinterest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentinel.ZoneOfInterest')),
            ],
        ),
    ]
