# -*- coding: utf-8 -*-
# Generated by Django 1.10.4.dev20161220101541 on 2017-01-20 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0016_worldparseprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldparseprocess',
            name='tilex',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worldparseprocess',
            name='tiley',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worldparseprocess',
            name='tilez',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
