# -*- coding: utf-8 -*-
# Generated by Django 1.10.4.dev20161220101541 on 2017-01-20 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0017_auto_20170120_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldparseprocess',
            name='zoneofinterest',
        ),
    ]
