# -*- coding: utf-8 -*-
# Generated by Django 1.10.4.dev20161220101541 on 2017-02-06 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0018_remove_worldparseprocess_zoneofinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldlayergroup',
            name='max_cloudy_pixel_percentage',
            field=models.FloatField(default=100),
        ),
    ]
