# -*- coding: utf-8 -*-
# Generated by Django 1.10.4.dev20161220101541 on 2017-02-16 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0019_worldlayergroup_max_cloudy_pixel_percentage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mgrstile',
            unique_together=set([('utm_zone', 'latitude_band', 'grid_square')]),
        ),
    ]
