# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0020_auto_20170216_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldlayergroup',
            name='currently_building',
        ),
        migrations.RemoveField(
            model_name='worldlayergroup',
            name='last_built',
        ),
        migrations.AlterField(
            model_name='worldlayergroup',
            name='worldlayers',
            field=models.ManyToManyField(editable=False, to='sentinel.WorldLayer'),
        ),
        migrations.AlterField(
            model_name='worldlayergroup',
            name='zonesofinterest',
            field=models.ManyToManyField(blank=True, help_text='What zones should this layer be built for?', to='sentinel.ZoneOfInterest'),
        ),
    ]
