# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 13:24
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0021_auto_20170615_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentineltile',
            name='tile_geom',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
