# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster_aggregation', '0016_auto_20170831_0618'),
        ('sentinel', '0022_sentineltile_tile_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldlayergroup',
            name='aggregationlayers',
            field=models.ManyToManyField(blank=True, help_text='What aggregation layers should this layer be built for?', to='raster_aggregation.AggregationLayer'),
        ),
    ]
