# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 13:50
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster_aggregation', '0016_auto_20170831_0618'),
        ('sentinel', '0023_worldlayergroup_aggregationlayers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentinelTileAggregationArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregationarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raster_aggregation.AggregationArea')),
                ('sentineltile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentinel.SentinelTile')),
            ],
        ),
    ]
