# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0024_sentineltileaggregationarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentineltileaggregationarea',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
