# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 16:53
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster_aggregation', '0016_auto_20170831_0618'),
        ('raster_api', '0016_auto_20170925_1653'),
        ('sentinel', '0025_sentineltileaggregationarea_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentinelTileAggregationLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('aggregationlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raster_aggregation.AggregationLayer')),
                ('sentineltile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentinel.SentinelTile')),
            ],
        ),
        migrations.RemoveField(
            model_name='sentineltileaggregationarea',
            name='aggregationarea',
        ),
        migrations.RemoveField(
            model_name='sentineltileaggregationarea',
            name='sentineltile',
        ),
        migrations.DeleteModel(
            name='SentinelTileAggregationArea',
        ),
        migrations.AlterUniqueTogether(
            name='sentineltileaggregationlayer',
            unique_together=set([('sentineltile', 'aggregationlayer')]),
        ),
    ]
