# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0026_auto_20170925_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentineltile',
            name='level',
            field=models.CharField(choices=[('l1c', 'Level 1C'), ('l2a', 'Level 2A')], default='l1c', max_length=10),
        ),
    ]
