# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0028_worldparseprocess_log'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorldLayerGroup',
            new_name='Composite',
        ),
    ]
