# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0031_auto_20180125_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='composite',
            name='official',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
