# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-26 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0032_composite_official'),
    ]

    operations = [
        migrations.AddField(
            model_name='composite',
            name='interval',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Custom', 'Custom')], default='Custom', editable=False, max_length=200),
        ),
    ]
