# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-05 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0033_composite_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='composite',
            name='sentineltiles',
            field=models.ManyToManyField(blank=True, help_text='Limit the composite to a specific set of sentinel tiles.', to='sentinel.SentinelTile'),
        ),
        migrations.AlterField(
            model_name='composite',
            name='max_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='composite',
            name='min_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
