# Generated by Django 2.0.2 on 2018-02-20 12:30

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0034_auto_20180205_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketparselog',
            name='schedulded',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 20, 12, 29, 50, 258123, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bucketparselog',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Finished', 'Finished'), ('Failed', 'Failed')], default='Finished', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bucketparselog',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
