# Generated by Django 2.0.2 on 2018-02-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0035_auto_20180220_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composite',
            name='all_zones',
        ),
        migrations.RemoveField(
            model_name='composite',
            name='zonesofinterest',
        ),
    ]
