# Generated by Django 2.0.2 on 2018-02-20 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raster_api', '0021_auto_20180220_1431'),
        ('sentinel', '0036_auto_20180220_1409'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZoneOfInterest',
        ),
    ]
