# Generated by Django 2.0.2 on 2018-02-20 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0037_delete_zoneofinterest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucketparselog',
            old_name='schedulded',
            new_name='scheduled',
        ),
    ]
