# Generated by Django 2.0.2 on 2018-02-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0038_auto_20180220_1508'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompositeBuildLog',
            new_name='CompositeTile',
        ),
    ]
