# Generated by Django 2.0.2 on 2018-02-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0039_auto_20180220_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentineltile',
            name='log',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sentineltile',
            name='status',
            field=models.CharField(choices=[('Unprocessed', 'Unprocessed'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Finished', 'Finished'), ('Failed', 'Failed')], default='Unprocessed', max_length=20),
        ),
    ]
