# Generated by Django 2.0.2 on 2018-02-21 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0040_auto_20180220_1640'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='compositetile',
            unique_together={('composite', 'tilez', 'tilex', 'tiley')},
        ),
    ]
