# Generated by Django 2.0.2 on 2018-02-21 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster_aggregation', '0018_aggregationlayer_extent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sentinel', '0041_auto_20180221_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField(default='')),
                ('status', models.CharField(choices=[('Unprocessed', 'Unprocessed'), ('Pending', 'Pending'), ('Ingesting Scenes', 'Ingesting Scenes'), ('Building Composite Tiles', 'Building Composite Tiles'), ('Finished', 'Finished'), ('Failed', 'Failed')], default='Unprocessed', max_length=50)),
                ('aggregationlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raster_aggregation.AggregationLayer')),
            ],
        ),
        migrations.RemoveField(
            model_name='composite',
            name='aggregationlayers',
        ),
        migrations.AddField(
            model_name='compositetile',
            name='scheduled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compositetile',
            name='status',
            field=models.CharField(choices=[('Unprocessed', 'Unprocessed'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Finished', 'Finished'), ('Failed', 'Failed')], default='Unprocessed', max_length=20),
        ),
        migrations.AddField(
            model_name='compositebuild',
            name='composite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentinel.Composite'),
        ),
        migrations.AddField(
            model_name='compositebuild',
            name='compositetiles',
            field=models.ManyToManyField(to='sentinel.CompositeTile'),
        ),
        migrations.AddField(
            model_name='compositebuild',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compositebuild',
            name='sentineltiles',
            field=models.ManyToManyField(to='sentinel.SentinelTile'),
        ),
    ]
