# Generated by Django 2.0.2 on 2018-02-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0042_auto_20180221_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composite',
            name='compositebands',
        ),
    ]
