# Generated by Django 2.0.2 on 2018-02-22 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0043_remove_composite_compositebands'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositeband',
            name='composite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sentinel.Composite'),
        ),
        migrations.AlterUniqueTogether(
            name='compositeband',
            unique_together={('composite', 'band')},
        ),
    ]
