# Generated by Django 2.0.2 on 2018-03-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0044_auto_20180222_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composite',
            name='official',
            field=models.BooleanField(default=False),
        ),
    ]
