# Generated by Django 2.0.2 on 2018-03-20 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0039_merge_20171116_1051'),
        ('sentinel', '0045_auto_20180315_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentinelTileSceneClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='raster.RasterLayer')),
                ('tile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sentinel.SentinelTile')),
            ],
        ),
    ]
