# Generated by Django 2.0.2 on 2018-05-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0048_auto_20180517_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositebuild',
            name='cloud_version',
            field=models.IntegerField(blank=True, help_text='Leave empty to use latest version.', null=True),
        ),
    ]
