# Generated by Django 2.0.2 on 2018-05-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0049_compositebuild_cloud_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositetile',
            name='cloud_version',
            field=models.IntegerField(blank=True, help_text='Leave empty to use latest version.', null=True),
        ),
    ]
