"""
Django settings for tesselo project.

Generated by 'django-admin startproject' using Django 1.10.4.dev20161220101541.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'j7$22brg^e@qpnnwtgw%1l@&=9=2yjbo-ky3ox-m_jgym*8iap'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', False) == 'True'

ALLOWED_HOSTS = ['*']

LOGIN_REDIRECT_URL = '/'

# Forward to ssl if not ssl recieved.
SECURE_SSL_REDIRECT = not DEBUG
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',

    'compressor',
    'rest_framework',
    'rest_framework.authtoken',
    'crispy_forms',
    'guardian',

    'raster',
    'raster_aggregation',
    'raster_api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tesselo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['tesselo/templates', ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'tesselo.wsgi.application'

# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ.get('DB_NAME', 'tesselo'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PORT': os.environ.get('DB_PORT', 5432),
        'PASSWORD': os.environ.get('DB_PASSWORD', None),
    }
}


# Password validation
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators

#AUTH_PASSWORD_VALIDATORS = [
    #{
        #'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    #},
    #{
        #'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    #},
    #{
        #'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    #},
    #{
        #'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    #},
#]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'guardian.backends.ObjectPermissionBackend',
)
# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'compressor.finders.CompressorFinder',
)
COMPRESS_ROOT = '/staticfiles'
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'frontend'),
)

# Compressor settings
COMPRESS_JS_FILTERS = [
    'compressor.filters.jsmin.JSMinFilter'
]

COMPRESS_CSS_FILTERS = [
    'compressor.filters.css_default.CssAbsoluteFilter',
    'compressor.filters.cssmin.CSSMinFilter'
]

COMPRESS_PRECOMPILERS = (
    ('text/scss', 'sass {infile} {outfile}'),
    ('text/less', 'lessc {infile} > {outfile}'),
)

COMPRESS_OFFLINE = True

# Celery settings
CELERY_BROKER_URL = 'amqp://guest:guest@localhost:5672//'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_ACKS_LATE = True

# Storage settings
DEFAULT_FILE_STORAGE='swift.storage.SwiftStorage'
if not DEBUG:
    STATICFILES_STORAGE ='swift.storage.StaticSwiftStorage'
#STATICFILES_STORAGE ='tesselo.swift.CachedStaticSwiftStorage'

SWIFT_CONTAINER_NAME='raster-api-media'
SWIFT_STATIC_CONTAINER_NAME='raster-api-static'

SWIFT_AUTH_URL="https://identity.open.softlayer.com/v3"
SWIFT_AUTH_VERSION='3'
SWIFT_USERNAME="admin_d25a27b832517e8876e43c348baa7d7e7a3a132e"
SWIFT_KEY="X/S]w_Ow]d(335Ko"
SWIFT_TENANT_NAME="object_storage_ad105e6c_9b10_4fd1_b00d_ba7ce36a88c6"
SWIFT_USER_DOMAIN_NAME='1100611'
SWIFT_PROJECT_DOMAIN_NAME='1100611'

#SWIFT_AUTH_VERSION="3"
#SWIFT_USERNAME="admin_d25a27b832517e8876e43c348baa7d7e7a3a132e",
#SWIFT_USERNAME="7f5e62716c64422a9d857fafa2a88d0b"
#SWIFT_USER_ID="7f5e62716c64422a9d857fafa2a88d0b"
#SWIFT_PASSWORD="X/S]w_Ow]d(335Ko"
#SWIFT_PROJECT_ID="5aefa817e5074528a22b16636238720a"
#SWIFT_USER_DOMAIN_ID="7f5e62716c64422a9d857fafa2a88d0b"
#SWIFT_USER_DOMAIN_NAME='1100611'
#SWIFT_PROJECT_DOMAIN_NAME='1100611'

#SWIFT_REGION_NAME="dallas"
#export OS_AUTH_VERSION=3


# Working command to make bucket public.
#export OS_USER_ID=7f5e62716c64422a9d857fafa2a88d0b
#export OS_PASSWORD=X/S]w_Ow]d(335Ko
#export OS_PROJECT_ID=5aefa817e5074528a22b16636238720a
#export OS_AUTH_URL=https://identity.open.softlayer.com/v3
#export OS_REGION_NAME=dallas
#export OS_IDENTITY_API_VERSION=3
#export OS_AUTH_VERSION=3
#swift post raster-api-static --read-acl ".r:*"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    )
}
