# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 10:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifier',
            name='legend',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}, editable=False),
        ),
    ]
