# Generated by Django 2.0.2 on 2018-09-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0001_initial'),
    ]

    operations = []
