# Generated by Django 2.0.2 on 2018-09-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classifier',
            options={'permissions': (('view_classifier', 'View classifier'),)},
        ),
        migrations.AlterModelOptions(
            name='predictedlayer',
            options={'permissions': (('view_predictedlayer', 'View predicted layer'),)},
        ),
        migrations.AlterModelOptions(
            name='trainingsample',
            options={'permissions': (('view_trainingsample', 'View training sample'),)},
        ),
    ]
