# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 11:42
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0028_worldparseprocess_log'),
        ('raster', '0039_merge_20171116_1051'),
        ('classify', '0002_auto_20170905_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('classifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classify.Classifier')),
                ('rasterlayer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='raster.RasterLayer')),
                ('sentineltile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sentinel.SentinelTile')),
                ('worldlayergroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sentinel.WorldLayerGroup')),
            ],
        ),
    ]
