# Generated by Django 2.0.5 on 2018-10-08 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0002_auto_20180925_1525'),
        ('classify', '0002_auto_20180925_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='composite',
            field=models.ForeignKey(blank=True, help_text='Is used as training data source if specified. If left blank, the original traininglayer pixels are used.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sentinel.Composite'),
        ),
        migrations.AddField(
            model_name='classifier',
            name='sentineltile',
            field=models.ForeignKey(blank=True, help_text='Is used as training data source if specified. If left blank, the original traininglayer pixels are used..', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sentinel.SentinelTile'),
        ),
    ]
