# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0003_predictedlayer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictedlayer',
            old_name='worldlayergroup',
            new_name='composite',
        ),
        migrations.RenameField(
            model_name='trainingsample',
            old_name='worldlayergroup',
            new_name='composite',
        ),
    ]
