# Generated by Django 2.0.5 on 2018-10-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0005_auto_20181009_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='needs_large_instance',
            field=models.BooleanField(default=False),
        ),
    ]
