# Generated by Django 2.0.2 on 2018-06-21 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0007_predictedlayer_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictedlayer',
            name='created',
        ),
    ]
