# Generated by Django 2.0.5 on 2018-12-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0007_auto_20181024_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininglayerexport',
            name='log',
            field=models.TextField(blank=True, default=''),
        ),
    ]
