# Generated by Django 2.0.5 on 2019-02-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0008_traininglayerexport_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='keras_model_json',
            field=models.TextField(blank=True, default='', help_text='A Keras model definition string created by model.to_json().', null=True),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='algorithm',
            field=models.CharField(choices=[('svm', 'Support Vector Machines'), ('lsvm', 'Linear Support Vector Machines'), ('rf', 'Random Forest'), ('nn', 'Neural Network'), ('svr', 'Support Vector Machines Regressor'), ('lsvr', 'Linear Support Vector Machines Regressor'), ('rfr', 'Random Forest Regressor'), ('nnr', 'Neural Network Regressor'), ('keras', 'Keras Model')], max_length=10),
        ),
    ]
