# Generated by Django 2.0.2 on 2018-06-22 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0009_auto_20180621_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='classifier',
            name='traininglayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classify.TrainingLayer'),
        ),
        migrations.AddField(
            model_name='trainingsample',
            name='traininglayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classify.TrainingLayer'),
        ),
    ]
