# Generated by Django 2.0.5 on 2019-02-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0009_auto_20190222_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifier',
            name='clf_args',
            field=models.TextField(blank=True, default='{}', help_text='Keyword arguments passed to the classifier. This will be ignored if clf_args is not a valid json string.'),
        ),
    ]
