# Generated by Django 2.1.7 on 2019-03-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0005_auto_20181026_1300'),
        ('classify', '0011_auto_20190227_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='composites',
            field=models.ManyToManyField(blank=True, help_text='Is used as training data source if specified. If left blank, the original traininglayer pixels are used.', related_name='old_composite', to='sentinel.Composite'),
        ),
    ]
