# Generated by Django 2.1.7 on 2019-03-11 12:08
from django.db import migrations


def forward(apps, schema_editor):
    Classifier = apps.get_model("classify", "Classifier")
    for clf in Classifier.objects.all():
        if clf.composite:
            clf.composites.add(clf.composite)


def backward(apps, schema_editor):
    Classifier = apps.get_model("classify", "Classifier")
    for clf in Classifier.objects.all():
        clf.composite = clf.composites.first()
        clf.save()


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0012_classifier_composites'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
