# Generated by Django 2.0.2 on 2018-06-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0013_auto_20180622_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traininglayer',
            options={'permissions': (('view_traininglayer', 'View training layer'),)},
        ),
    ]
