# Generated by Django 2.1.7 on 2019-08-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0015_classifier_collected_pixels'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='training_all_touched',
            field=models.BooleanField(default=True, help_text='Sets the all_touched flag when rasterizing the training samples.'),
        ),
    ]
