# Generated by Django 2.0.2 on 2018-07-24 11:12

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0016_auto_20180625_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifierAccuracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), default=[], size=None)),
                ('predicted', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], size=None)),
                ('control', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], size=None)),
                ('accuracy_matrix', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], size=None), default=[], size=None)),
                ('cohen_kappa', models.FloatField(default=0)),
                ('accuracy_score', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='classifier',
            name='splitfraction',
            field=models.FloatField(default=0, help_text='Fraction of pixels that should be reserved for validation.'),
        ),
        migrations.AddField(
            model_name='traininglayer',
            name='dependent',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], size=None), default=[], size=None),
        ),
        migrations.AddField(
            model_name='traininglayer',
            name='explanatory',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
        migrations.AddField(
            model_name='traininglayer',
            name='legend',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}, editable=False),
        ),
        migrations.AddField(
            model_name='classifieraccuracy',
            name='classifier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classify.Classifier'),
        ),
    ]
