# Generated by Django 2.1.7 on 2019-09-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0017_predictedlayer_legend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifier',
            name='algorithm',
            field=models.CharField(choices=[('svm', 'Support Vector Machines'), ('lsvm', 'Linear Support Vector Machines'), ('rf', 'Random Forest'), ('nn', 'Neural Network'), ('svr', 'Support Vector Machines Regressor'), ('lsvr', 'Linear Support Vector Machines Regressor'), ('rfr', 'Random Forest Regressor'), ('nnr', 'Neural Network Regressor'), ('keras', 'Keras Model'), ('kerasr', 'Keras Model Regressor')], max_length=10),
        ),
    ]
