# Generated by Django 2.0.2 on 2018-07-26 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0017_auto_20180724_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifier',
            name='legend',
        ),
    ]
