# Generated by Django 2.1.7 on 2020-01-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0018_auto_20190910_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traininglayerexport',
            name='composite',
        ),
        migrations.RemoveField(
            model_name='traininglayerexport',
            name='sentineltile',
        ),
        migrations.RemoveField(
            model_name='traininglayerexport',
            name='traininglayer',
        ),
        migrations.DeleteModel(
            name='TrainingLayerExport',
        ),
    ]
