# Generated by Django 2.0.2 on 2018-07-31 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0018_remove_classifier_legend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traininglayer',
            name='dependent',
        ),
        migrations.RemoveField(
            model_name='traininglayer',
            name='explanatory',
        ),
    ]
