# Generated by Django 2.1.7 on 2020-01-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0019_auto_20200117_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='look_back_steps',
            field=models.PositiveIntegerField(default=0, help_text='Number of composite steps back from sample date should be included in training and predicting data collection. Ignored if zero.'),
        ),
    ]
