# Generated by Django 2.0.2 on 2018-07-31 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0019_auto_20180731_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifieraccuracy',
            name='control',
        ),
        migrations.RemoveField(
            model_name='classifieraccuracy',
            name='predicted',
        ),
        migrations.RemoveField(
            model_name='classifieraccuracy',
            name='selector',
        ),
    ]
