# Generated by Django 2.0.2 on 2018-08-09 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0020_auto_20180731_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedLayerChunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_index', models.IntegerField()),
                ('to_index', models.IntegerField()),
                ('status', models.CharField(choices=[('Unprocessed', 'Unprocessed'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Finished', 'Finished'), ('Failed', 'Failed')], default='Unprocessed', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='predictedlayer',
            name='chunks_count',
        ),
        migrations.RemoveField(
            model_name='predictedlayer',
            name='chunks_done',
        ),
        migrations.AddField(
            model_name='predictedlayerchunk',
            name='predictedlayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classify.PredictedLayer'),
        ),
    ]
