# Generated by Django 2.0.2 on 2018-08-10 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster_aggregation', '0020_auto_20180308_0435'),
        ('classify', '0021_auto_20180809_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedlayer',
            name='aggregationlayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='raster_aggregation.AggregationLayer'),
        ),
    ]
