# Generated by Django 2.1.7 on 2020-01-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0021_trainingsample_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='split_by_polygon',
            field=models.BooleanField(default=False, help_text='Reserve pixels at the polygon level, i.e. keep a percentage of training polygons as verification data.'),
        ),
        migrations.AddField(
            model_name='classifier',
            name='split_random_seed',
            field=models.PositiveIntegerField(blank=True, help_text='Fix random seed for train and test split to make verification more comparable.', null=True),
        ),
    ]
