# Generated by Django 2.1.7 on 2020-01-21 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0007_compositebuildschedule_continuous_scene_ingestion'),
        ('classify', '0022_auto_20200120_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedlayer',
            name='composites',
            field=models.ManyToManyField(to='sentinel.Composite'),
        ),
        migrations.AlterField(
            model_name='predictedlayer',
            name='composite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_composite', to='sentinel.Composite'),
        ),
    ]
