# Generated by Django 2.0.2 on 2018-09-05 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0022_predictedlayer_aggregationlayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingLayerExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to='clouds/traininglayer_exports')),
                ('created', models.DateTimeField(auto_now=True)),
                ('traininglayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classify.TrainingLayer')),
            ],
        ),
    ]
