# Generated by Django 2.0.2 on 2018-09-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0023_traininglayerexport'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='band_names',
            field=models.CharField(default='B02,B03,B04,B05,B06,B07,B08,B8A,B09,B10,B11,B12', help_text='Comma-separated list of band names and layer ids. If an integer value is added, it is assumed to be a rasterlayer id that should be included in the export.', max_length=500),
        ),
    ]
