# Generated by Django 2.1.7 on 2020-01-21 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0024_auto_20200121_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictedlayer',
            name='composite',
        ),
    ]
