# Generated by Django 2.1.7 on 2020-02-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0025_remove_predictedlayer_composite'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedlayer',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
