# Generated by Django 2.1.7 on 2020-02-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0026_predictedlayer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictedlayer',
            name='name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
