# Generated by Django 2.1.7 on 2020-02-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0027_auto_20200219_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictedlayer',
            name='composites',
            field=models.ManyToManyField(blank=True, to='sentinel.Composite'),
        ),
    ]
