# Generated by Django 2.1.7 on 2020-02-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0028_auto_20200219_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedlayer',
            name='max_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='predictedlayer',
            name='min_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
