# Generated by Django 3.0.5 on 2020-06-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0033_classifier_wrap_keras_with_sklearn'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingpixels',
            name='patch_size',
            field=models.IntegerField(default=100, help_text='Determines how many training sample geometries should be bundeled into a patch.'),
        ),
    ]
