# Generated by Django 3.0.7 on 2020-06-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0036_auto_20200615_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedlayer',
            name='chunk_size',
            field=models.IntegerField(default=100, help_text='Number of tiles to process per task. Reduce size for predictions with many composites.'),
        ),
    ]
