# Generated by Django 3.0.7 on 2020-06-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0037_predictedlayer_chunk_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='auto_class_weights',
            field=models.BooleanField(default=False, help_text='Automatically compute class weights and use as fit parameters in Keras.'),
        ),
    ]
