# Generated by Django 3.0.8 on 2020-09-09 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0038_classifier_auto_class_weights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifier',
            name='needs_gpu_instance',
        ),
    ]
