# Generated by Django 3.0.8 on 2020-07-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0038_classifier_auto_class_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedlayer',
            name='vectortiles',
            field=models.BooleanField(default=False),
        ),
    ]
