# Generated by Django 3.0.8 on 2020-09-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0039_remove_classifier_needs_gpu_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingpixels',
            name='flatten',
            field=models.BooleanField(default=True),
        ),
    ]
