# Generated by Django 2.0.2 on 2018-09-25 14:18

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.hstore
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='Sentinel1Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField()),
                ('prefix', models.TextField(unique=True)),
                ('mission_id', models.TextField()),
                ('product_type', models.TextField()),
                ('mode', models.TextField()),
                ('polarization', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField()),
                ('absolute_orbit_number', models.IntegerField()),
                ('mission_datatake_id', models.IntegerField()),
                ('product_unique_identifier', models.TextField()),
                ('sci_hub_id', models.TextField()),
                ('footprint', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326)),
                ('filename_map', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
        ),
    ]
