# Generated by Django 2.1.7 on 2020-02-07 10:29

from django.contrib.gis.geos import MultiPolygon
from django.db import migrations


def forward(apps, schema_editor):
    Sentinel1Tile = apps.get_model("sentinel_1", "Sentinel1Tile")
    for stile in Sentinel1Tile.objects.all():
        if stile.footprint:
            stile.footprint_multi = MultiPolygon(stile.footprint)
            stile.save()


def backward(apps, schema_editor):
    Sentinel1Tile = apps.get_model("sentinel_1", "Sentinel1Tile")
    for stile in Sentinel1Tile.objects.all():
        if stile.footprint_multi:
            stile.footprint = stile.footprint_multi[0]
            stile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel_1', '0003_sentinel1tile_footprint_multi'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
