# Generated by Django 2.1.7 on 2020-02-07 10:29

from django.db import migrations
from django.db.models import F, Func


def forward(apps, schema_editor):
    Sentinel1Tile = apps.get_model("sentinel_1", "Sentinel1Tile")
    Sentinel1Tile.objects.all().update(footprint_multi=Func(F('footprint'), function='ST_Multi'))


def backward(apps, schema_editor):
    # Ignore backward migration path.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel_1', '0003_sentinel1tile_footprint_multi'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
