# Generated by Django 2.1.7 on 2020-02-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel_1', '0004_auto_20200207_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentinel1tile',
            name='footprint',
        ),
    ]
