# Generated by Django 2.1.7 on 2020-02-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel_1', '0005_remove_sentinel1tile_footprint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentinel1tile',
            old_name='footprint_multi',
            new_name='footprint',
        ),
    ]
