# Generated by Django 2.0.2 on 2018-04-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NAIPQuadrangle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=500, unique=True)),
                ('lat', models.IntegerField(db_index=True)),
                ('lon', models.IntegerField(db_index=True)),
                ('subquad', models.IntegerField(db_index=True)),
                ('corner', models.CharField(choices=[('nw', 'North West'), ('ne', 'North East'), ('sw', 'South West'), ('se', 'South East')], db_index=True, max_length=2)),
                ('source', models.CharField(choices=[('rgbir', '4-Band Uncompressed'), ('rgb', '3-Band JPEG Compressed and tiled internally')], db_index=True, max_length=10)),
                ('state', models.CharField(max_length=50)),
                ('date', models.DateField(db_index=True)),
                ('resolution', models.CharField(max_length=50)),
            ],
        ),
    ]
